config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'mains#index'
  resources 'mains' do
    collection do
      get 'auth_user'
      get 'login'
      delete 'logout'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/settings.rb
# RailsSettings Model
class Settings < RailsSettings::Base
  source Rails.root.join("config/app.yml")
  namespace Rails.env
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :user_access_token, :user_instagram_code, :user_info

  # Check user login status
  def check_login
    unless (session[:access_token] && session[:instagram_code])
      redirect_to login_mains_path
    end
  end

  # load info easy way
  def user_access_token  
    session[:access_token]
  end

  def user_instagram_code    
    session[:instagram_code]
  end

  def user_info
    session[:user_info]
  end
  
end

app/controllers/mains_controller.rb
class MainsController < ApplicationController
  before_action :check_login, only: :index

  def index
    # get instagram photos
    begin 
      url = "https://api.instagram.com/v1/users/self/media/recent/?access_token=#{user_access_token}"
      instagram_response = JSON.parse(RestClient.get url)
      # handle empty instagram photos situation
      unless instagram_response['data'].present?
        @photos = {}
      else
        @photos = instagram_response['data']
      end
      # get user info for profile pic and user name
      @user_info = user_info
    rescue RestClient::ExceptionWithResponse => err
      puts err
      redirect_to login_mains_path, flash: {notice: "Please Login Again."}
    end  
  end

  def login
    redirect_to root_path if user_access_token.present?
    @client_id = Settings['instagram.client_id']
    @redirect_uri =  Settings['instagram.redirect_uri']
  end

  def logout
    reset_session
    redirect_to login_mains_path
  end

  def auth_user
    # auth instagram login callbok
    if params['error'] || params['error_type']
      # login failed 
      puts params['error']
      flash[:notice] = "Instagram Sign in Failed."
    else
      # sotre code in session
      session[:instagram_code] = params['code']
      # get user access_token and user_info
      url = "https://api.instagram.com/oauth/access_token"
      request_params = {
        client_id: Settings['instagram.client_id'],
        client_secret: Settings['instagram.client_secret'],
        redirect_uri: Settings['instagram.redirect_uri'],
        grant_type: 'authorization_code',
        code: params['code']
      }
      
      begin
        response = JSON.parse(RestClient.post url, request_params)
        # store necessary info in session
        session[:access_token] = response['access_token']
        session[:user_info] = response['user']
      rescue RestClient::ExceptionWithResponse => err
        # auth failed
        puts err
        redirect_to login_mains_path, flash: {notice: "Instagram Auth Failed."}
        return
      end
    end  
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mains_helper.rb
module MainsHelper
  
  def active_first_item(index)
    'active' if index ==0
  end

  def show_instagram_photos(photo)    
    case photo['type']
      # show video source
      when "video"
        render 'partial/video_source', soruce: photo
      # show mulitiple images source
      when "carousel"
        render 'partial/carousel_source', source: photo
      # show one image source
      when "image"
        render 'partial/image_source', source: photo
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <title>ShowoffTechTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= params[:action] %>">
    <div class="wrapper">
      <%= yield %>
    </div>
  </body>
</html>

app/views/mains/index.html.erb
<%= render 'partial/header' %>

<!-- show instagram photos -->
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <%= "<h1 class='text-center'>You don't have any instagram photos.</h1>".html_safe  if @photos.empty?%>
      <% @photos.each do |photo| %>
        <div class="col-md-4">
          <section class="panel photo-group">
            <div class="text-center">
              <%= show_instagram_photos(photo)%>
            </div>
          </section>
        </div>
      <%end%>
    </div>
  </div>
</div>

app/views/mains/login.html.erb
<div class="container">
  <div class="row">  
    <div class="col-md-12">
      <%= render 'partial/error_alert' if notice.present?%>

      <div class="login-wrap col-md-8 col-sm-10 col-lg-8 col-md-offset-2 col-lg-offset-2 col-sm-offset-1">
        <div class="logo_img">
          <img class="img-rounded" src="https://www.jobs.ie/logos/-2722199.png" alt="Showoff_logo">
        </div>
        <a class="btn btn-lg btn-block btn-instagram pointer" 
        href="https://api.instagram.com/oauth/authorize/?client_id=<%=@client_id%>&redirect_uri=<%=@redirect_uri%>&response_type=code">
          <i class="fa fa-instagram"></i> Sign in with Instagram 
        </a>
      </div>
    </div>
  </div>
</div>

app/views/partial/_carousel_source.html.erb
<div id="<%=source['created_time']%>" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner instagram-img">
    <% source['carousel_media'].each_with_index do |image, index|%>
        <div class="item <%= active_first_item(index)%>">
          <img class="instagram-img" src="<%=image['images']['standard_resolution']['url']%>">
        </div>
    <%end%>
  </div>
  <a class="left carousel-control" href="#<%=source['created_time']%>" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#<%=source['created_time']%>" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/partial/_error_alert.html.erb
<div class="alert alert-danger col-md-12" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close" style="font-size: 16px">
    <span aria-hidden="true">&times;</span>
  </button>
  <p><%= notice %></p>
</div>

app/views/partial/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <a class="navbar-brand">
      <img class="img-rounded nav-user-pic" src="https://www.jobs.ie/logos/-2722199.png" alt="Showoff_logo" width="30" height="30">
      TechTest
    </a>
    <div class="dropdown show navbar-brand navbar-right">
      <a class="dropdown-toggle" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <img class="img-circle nav-user-pic" src="<%=@user_info['profile_picture']%>" alt="user_profile_picture" width="30" height="30"> 
        <%=@user_info['full_name']%>
      </a>
      <div class="dropdown-menu dropdown-rwd" aria-labelledby="dropdownMenuLink">
        <%= link_to 'Logout' , logout_mains_path , method: :delete, class: ['btn btn-block btn-danger'] %>
      </div>
    </div>
  </div>
</nav>

app/views/partial/_image_source.html.erb
<img class="instagram-img" src="<%=source['images']['standard_resolution']['url']%>" alt="image">

app/views/partial/_video_source.html.erb
<video width="100%" height="250px" controls>
  <source src="<%=soruce['videos']['standard_resolution']['url']%>" type="video/mp4">
</video>